### PR TITLE
Emoji gems + minor updates

### PR DESCRIPTION
**Pull request by solyarisoftware**

### CODE REVIEW

**Comment by diasks2** [comment]
Thanks! Could you push a commit that resolves the conflicts so that I can merge from Github?

**Comment by solyarisoftware** [comment]
Hi Kevin

in facts I resolved conflicts in the pull request I already done: 
here all differences: https://github.com/diasks2/ruby-nlp/pull/21/files

I'm not expert using github (/new github feature updates), but I presume you could just review/approve my pull request (with the review changes green button, and approving here).

The reason of the "conflict" was becuase in an intermediate file I insert some chars for mistake/typo. Afterward i correct the error and finally I did the pull request.

Plese let me know if I can help

thanks
giorgio

**Comment by solyarisoftware** [comment]
BTW, maybe just because this:
https://github.com/diasks2/ruby-nlp/pull/21/files#diff-04c6e90faac2675aa89e2176d2eec7d8L167
:) ... moving a line, I substituted a '-' with a '*', in a list. nothing changes.

**Comment by diasks2** [comment]
It is most likely because I made some changes after your previous pull request, so your local master is not up to date. Try pulling the latest from Github and merging master into your branch.

**Comment by solyarisoftware** [comment]
Hi Kevin, see pull request #22!

**Pull request closed without merging**
