### PR TITLE
Added a bunch of entries (BabelNet, WordNet, tensorflow, Amazon Echo, etc.)

### PR DESCRIPTION
**Pull request by solyarisoftware**
Hi Kevin!
I submit here a bunch of new entries. I guess you will appreciate above all BabelNet :), a project by Italian professor Roberto Navigli. I feel this project deserve a special attention.

I added a new paragraph "databases" ... my classification is of course opinable and please feel free to rearrange items as you retain better!

Maybe interesting also the Google Tensorflow APis

Please note I had no time to verify these projects, but I believe it's a good idea to trace them in your Ruby-nlp repo.

By the end of the year I'll probably submit my project "naif", a microframework in pure Ruby to develop simpe workflow-oriented chatbots.

keep in touch
King regards
giorgio

### CODE REVIEW

**Comment by diasks2** [comment]
Awesome! Thanks for all your contributions!

**Comment by solyarisoftware** [comment]
Thanks Kevin, 
BTW, I'm working a bit around emoji as a nowadays (see teenagers) way con "conversate". This topic is probably borderline with the main NLP subject, nevertheless, in my opinion, emojii are also NLP...

What do you think about it?
In case you agree I submit here few great gems I just discovered. 

cheers
giorgio

**Comment by diasks2** [comment]
Hi Giorgio,

Good question. I think it is kind of a borderline NLP subject, but I have definitely used emoji related gems and had to think about emoji in different NLP gems I have worked on, such as the tokenizer. So I think it might be good to have a section devoted to it.

Kevin

**Comment by solyarisoftware** [comment]
Hi Kevin,

ok, I submit asap some related gems,

thanks
giorgio

**Pull request merged**
