### PR TITLE
Adding a brand new tokenizer

### PR DESCRIPTION
**Pull request by thisiscetin**
I would be glad if you add my new gem Textoken to your valuable collection. Thanks.

### CODE REVIEW

**Comment by diasks2** [comment]
Cool gem! Thanks for adding it!

**Comment by thisiscetin** [comment]
Thank you very much!

**Comment by diasks2** [comment]
I'm just going to change the order slightly, as apart from the NLP presentations section, I am trying to keep them in alphabetical order by gem name.

**Comment by thisiscetin** [comment]
sorry, I did not realize the default sorting

**Pull request merged**
